name: pusher_js
description: Pusher wrapper for Dart
version: 1.3.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/pusher-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'
