name: pusher_js
description: Pusher wrapper for Dart
version: 1.0.2
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/pusher-dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
